name: "Exam 7 Notes"
description: "CAS Exam 7 Notes"

baseurl: /Exam-7-2016-Notes

paginate: 30

markdown: rdiscount
permalink: pretty
highlighter: rouge
github: [Repository metadata]

gems: [jekyll-paginate]
